# 2️⃣ IPL Data Analysis 🏏

In [3]:
import pandas as pd
ipl=pd.read_csv('ipl 2017.csv')
ipl.head()

,Match ID,Date,Venue,Team1,Team2,Toss Winner,Toss Decision,Stage,First Innings Score,First Innings Wicket,Second Innings score,Second Innings Wicket,Match Winner,Won by,Margin,Player of the match
0,1,05-04-2017,"Rajiv Gandhi International Cricket Stadium, Hy...",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,Field,Group,207.0,4.0,172.0,10.0,Sunrisers Hyderabad,Runs,35.0,Yuvraj Singh
1,2,06-04-2017,"Maharashtra Cricket Association Stadium, Pune",Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,Field,Group,184.0,8.0,187.0,3.0,Rising Pune Supergiants,Wickets,7.0,Steve Smith
2,3,07-04-2017,"Saurashtra Cricket Association Stadium, Rajkot",Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,Field,Group,183.0,4.0,184.0,0.0,Kolkata Knight Riders,Wickets,10.0,Chris Lynn
3,4,08-04-2017,"Holkar Cricket Stadium, Indore",Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,Field,Group,163.0,6.0,164.0,4.0,Kings XI Punjab,Wickets,6.0,Glenn Maxwell
4,5,08-04-2017,"M. Chinnaswamy Stadium, Bangalore",Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,Bat,Group,157.0,8.0,142.0,9.0,Royal Challengers Bangalore,Runs,15.0,Kedar Jadhav

In [9]:
print(ipl.columns)

Index(['Match ID', 'Date', 'Venue', 'Team1', 'Team2', 'Toss Winner',
       'Toss Decision', 'Stage', 'First Innings Score', 'First Innings Wicket',
       'Second Innings score', 'Second Innings Wicket', 'Match Winner',
       'Won by', 'Margin', 'Player of the match'],
      dtype='str')

In [10]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Match ID               60 non-null     int64
 1   Date                   60 non-null     str
 2   Venue                  60 non-null     str
 3   Team1                  60 non-null     str
 4   Team2                  60 non-null     str
 5   Toss Winner            59 non-null     str
 6   Toss Decision          59 non-null     str
 7   Stage                  59 non-null     str
 8   First Innings Score    59 non-null     float64
 9   First Innings Wicket   59 non-null     float64
 10  Second Innings score   59 non-null     float64
 11  Second Innings Wicket  59 non-null     float64
 12  Match Winner           59 non-null     str
 13  Won by                 59 non-null     str
 14  Margin                 58 non-null     float64
 15  Player of the match    59 non-null     str
dtypes: float64(5), int64(1), str(10)
memory usage: 7.6 KB

In [12]:
ipl.isnull().sum()

Match ID                 0
Date                     0
Venue                    0
Team1                    0
Team2                    0
Toss Winner              1
Toss Decision            1
Stage                    1
First Innings Score      1
First Innings Wicket     1
Second Innings score     1
Second Innings Wicket    1
Match Winner             1
Won by                   1
Margin                   2
Player of the match      1
dtype: int64

In [14]:
ipl.describe()

,Match ID,First Innings Score,First Innings Wicket,Second Innings score,Second Innings Wicket,Margin
count,60.000000,59.000000,59.000000,59.000000,59.000000,58.000000
mean,30.500000,165.779661,6.254237,152.338983,5.745763,17.103448
std,17.464249,30.887486,2.286340,37.248749,2.916027,25.345812
min,1.000000,67.000000,2.000000,48.000000,0.000000,1.000000
25%,15.750000,153.500000,4.000000,138.500000,3.000000,6.000000
50%,30.500000,163.000000,6.000000,159.000000,6.000000,7.500000
75%,45.250000,186.000000,8.000000,176.500000,8.500000,15.000000
max,60.000000,230.000000,10.000000,223.000000,10.000000,146.000000