In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("diabetes_risk_prediction_dataset.csv")

In [4]:
df.head()

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk,BMI_CATEGORY
0,1,32.0,Male,Mexico,182.1,65.8,19.8,71.2,88.4,10.4,...,No,Good,Retired,Rural,4.4,60,Healthy Diet Plan,Yes,Moderate,Normal
1,2,42.0,Other,Saudi Arabia,148.5,101.2,45.9,121.8,247.3,11.3,...,Yes,Average,Government,Rural,2.1,99,Begin Diabetes Management Plan,Yes,High,Obese
2,3,89.0,Other,Argentina,158.1,NaN,37.9,131.8,141.9,6.3,...,No,Average,Government,Urban,2.8,80,Strict Blood Sugar Monitoring,Yes,High,Obese
3,4,87.0,Other,United States,190.9,95.9,26.3,99.1,90.1,7.4,...,No,Average,Business,Rural,1.5,82,Begin Diabetes Management Plan,Yes,High,Overweight
4,5,27.0,Other,Australia,156.9,101.9,41.4,77.1,93.8,12.0,...,Yes,Poor,Private,Rural,1.6,93,Begin Diabetes Management Plan,Yes,High,Obese

In [5]:
df.shape

(50000, 42)

In [6]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Country', 'Height_cm', 'Weight_kg',
       'BMI', 'Waist_Circumference_cm', 'Blood_Glucose', 'HbA1c',
       'Fasting_Blood_Sugar', 'Insulin_Level', 'Blood_Pressure_Systolic',
       'Blood_Pressure_Diastolic', 'Total_Cholesterol', 'HDL', 'LDL',
       'Triglycerides', 'Heart_Rate', 'Physical_Activity_Level',
       'Exercise_Hours_Per_Week', 'Daily_Walking_Minutes', 'Diet_Quality',
       'Sugar_Intake_Level', 'Sleep_Hours', 'Stress_Level', 'Smoking_Status',
       'Alcohol_Consumption', 'Family_History_Diabetes', 'Hypertension',
       'Heart_Disease', 'Fatty_Liver', 'PCOS', 'Medication_Adherence',
       'Work_Type', 'Residence_Type', 'Daily_Water_Intake_L',
       'Diabetes_Risk_Score', 'AI_Health_Recommendation',
       'Doctor_Consultation_Needed', 'Diabetes_Risk', 'BMI_CATEGORY'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  50000 non-null  int64
 1   Age                         50000 non-null  float64
 2   Gender                      50000 non-null  object
 3   Country                     50000 non-null  object
 4   Height_cm                   50000 non-null  float64
 5   Weight_kg                   50000 non-null  float64
 6   BMI                         50000 non-null  float64
 7   Waist_Circumference_cm      50000 non-null  float64
 8   Blood_Glucose               50000 non-null  float64
 9   HbA1c                       50000 non-null  float64
 10  Fasting_Blood_Sugar         50000 non-null  float64
 11  Insulin_Level               50000 non-null  float64
 12  Blood_Pressure_Systolic     50000 non-null  int64
 13  Blood_Pressure_Diastolic    50000 non-null  int64
 14  Total_Cholesterol           50000 non-null  float64
 15  HDL                         50000 non-null  float64
 16  LDL                         50000 non-null  float64
 17  Triglycerides               50000 non-null  float64
 18  Heart_Rate                  50000 non-null  int64
 19  Physical_Activity_Level     50000 non-null  object
 20  Exercise_Hours_Per_Week     50000 non-null  float64
 21  Daily_Walking_Minutes       50000 non-null  float64
 22  Diet_Quality                50000 non-null  object
 23  Sugar_Intake_Level          50000 non-null  object
 24  Sleep_Hours                 50000 non-null  float64
 25  Stress_Level                50000 non-null  object
 26  Smoking_Status              50000 non-null  object
 27  Alcohol_Consumption         50000 non-null  object
 28  Family_History_Diabetes     50000 non-null  object
 29  Hypertension                50000 non-null  object
 30  Heart_Disease               50000 non-null  object
 31  Fatty_Liver                 50000 non-null  object
 32  PCOS                        50000 non-null  object
 33  Medication_Adherence        50000 non-null  object
 34  Work_Type                   50000 non-null  object
 35  Residence_Type              50000 non-null  object
 36  Daily_Water_Intake_L        50000 non-null  float64
 37  Diabetes_Risk_Score         50000 non-null  int64
 38  AI_Health_Recommendation    50000 non-null  object
 39  Doctor_Consultation_Needed  50000 non-null  object
 40  Diabetes_Risk               50000 non-null  object
 41  BMI_CATEGORY                50000 non-null  object
dtypes: float64(17), int64(5), object(20)
memory usage: 16.0+ MB

In [13]:
df.describe()

,Patient_ID,Age,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,Fasting_Blood_Sugar,Insulin_Level,...,Total_Cholesterol,HDL,LDL,Triglycerides,Heart_Rate,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Sleep_Hours,Daily_Water_Intake_L,Diabetes_Risk_Score
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.00000,50000.000000,50000.000000
mean,25000.500000,53.87238,170.017706,87.447702,30.924056,99.960790,159.905144,8.488532,142.607294,23.476724,...,220.173262,57.370296,135.016234,229.542394,85.124260,5.016764,89.92820,6.50088,2.998842,74.043920
std,14433.901067,21.02487,14.025535,23.763593,10.290091,23.086579,51.539079,2.267625,44.681799,12.403841,...,57.212768,18.532543,48.641767,97.247581,20.390334,2.818052,51.00243,1.98647,1.152273,15.598327
min,1.000000,18.00000,145.000000,45.000000,11.900000,60.000000,70.000000,4.500000,65.000000,2.000000,...,120.000000,25.000000,50.000000,60.000000,50.000000,0.000000,0.00000,3.00000,1.000000,13.000000
25%,12500.750000,36.00000,158.300000,67.700000,22.700000,80.000000,115.500000,6.600000,103.900000,12.800000,...,170.775000,41.600000,93.300000,146.400000,68.000000,2.600000,46.80000,4.80000,2.000000,64.000000
50%,25000.500000,54.00000,170.000000,87.300000,30.000000,99.800000,159.900000,8.500000,142.600000,23.400000,...,220.400000,57.300000,135.100000,229.500000,85.000000,5.000000,89.80000,6.50000,3.000000,75.000000
75%,37500.250000,72.00000,181.800000,107.200000,37.800000,119.900000,204.200000,10.400000,181.500000,34.300000,...,269.500000,73.200000,176.900000,312.900000,103.000000,7.400000,133.40000,8.20000,4.000000,86.000000
max,50000.000000,90.00000,195.000000,130.000000,61.700000,140.000000,250.000000,12.500000,220.000000,45.000000,...,320.000000,90.000000,220.000000,400.000000,120.000000,10.000000,180.00000,10.00000,5.000000,100.000000

In [11]:
df.isnull().sum()

Patient_ID                    0
Age                           0
Gender                        0
Country                       0
Height_cm                     0
Weight_kg                     0
BMI                           0
Waist_Circumference_cm        0
Blood_Glucose                 0
HbA1c                         0
Fasting_Blood_Sugar           0
Insulin_Level                 0
Blood_Pressure_Systolic       0
Blood_Pressure_Diastolic      0
Total_Cholesterol             0
HDL                           0
LDL                           0
Triglycerides                 0
Heart_Rate                    0
Physical_Activity_Level       0
Exercise_Hours_Per_Week       0
Daily_Walking_Minutes         0
Diet_Quality                  0
Sugar_Intake_Level            0
Sleep_Hours                   0
Stress_Level                  0
Smoking_Status                0
Alcohol_Consumption           0
Family_History_Diabetes       0
Hypertension                  0
Heart_Disease                 0
Fatty_Liver                   0
PCOS                          0
Medication_Adherence          0
Work_Type                     0
Residence_Type                0
Daily_Water_Intake_L          0
Diabetes_Risk_Score           0
AI_Health_Recommendation      0
Doctor_Consultation_Needed    0
Diabetes_Risk                 0
BMI_CATEGORY                  0
dtype: int64

In [8]:
num_cols = [
    'Age',
    'Height_cm',
    'Weight_kg',
    'Blood_Glucose',
    'HbA1c',
    'Total_Cholesterol',
    'HDL',
    'LDL',
    'Triglycerides',
    'Exercise_Hours_Per_Week',
    'Daily_Walking_Minutes',
    'Sleep_Hours'
]
for col in num_cols:
    df[col]=df[col].fillna(df[col].median())

In [10]:
cat_cols = [
    'Physical_Activity_Level',
    'Medication_Adherence'
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])