In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [8]:
df=pd.read_csv("train.txt",sep=";",header=None,names=['text','emotion'])

In [9]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [10]:

df.isnull().sum()

text       0
emotion    0
dtype: int64

In [11]:
unique_emotions = df['emotion'].unique()

emotion_numbers = {}

for i, emo in enumerate(unique_emotions):
    emotion_numbers[emo] = i

df['emotion'] = df['emotion'].map(emotion_numbers)

print(emotion_numbers)
print(df['emotion'].value_counts())

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}
emotion
5    5362
0    4666
1    2159
4    1937
2    1304
3     572
Name: count, dtype: int64

In [12]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [13]:
df['text']=df['text'].apply(lambda x :x.lower())

In [14]:
import string

In [15]:
def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

In [16]:
df['text']=df['text'].apply(remove_punc)

In [17]:

def remove_numbers(txt):
    return txt.translate(str.maketrans('', '', string.digits))

In [18]:
df['text']=df['text'].apply(remove_numbers)

In [19]:
import re

def clean_text(txt):
    txt = re.sub(r'https?://\S+|www\.\S+', '', txt)  # remove URLs
    txt = re.sub(r'\d+', '', txt)                    # remove numbers
    return txt

In [20]:
df['text']=df['text'].apply(clean_text)

In [24]:
import emoji

def remove_emojis(txt):
    return emoji.replace_emoji(txt, replace='')

In [23]:
pip install emoji

Defaulting to user installation because normal site-packages is not writeable
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/608.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/608.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/608.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/608.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/608.4 kB ? eta -:--:--
   -------------------------------- ----- 524.3/608.4 kB 260.1 kB/s eta 0:00:01
   ---------------------------------------- 608.4/608.4 kB 259.4 kB/s  0:00:02
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
df['text']=df['text'].apply(remove_emojis)

In [30]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rajes\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [31]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(txt):
    return ' '.join(
        word for word in txt.split()
        if word.lower() not in stop_words
    )

In [ ]:
df['text']=df['text'].apply(clean_text)

In [27]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in C:\Users\rajes\AppData\Roaming\Python\Python313\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\rajes\AppData\Roaming\Python\Python313\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in C:\Users\rajes\AppData\Roaming\Python\Python313\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2026.7.19-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\rajes\AppData\Roaming\Python\Python313\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\rajes\AppData\Roaming\Python\Python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------- ---------------------------- 0.5/1.8 MB 219.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------- ---------------------- 0.8/1.8 MB 180.2 kB/s eta 0:00:06
   ----------------------- ---------------- 1.0/1.8 MB 188.2 kB/s eta 0:00:04
   ----------------------- ---------------- 1.0/1.8 MB 188.2 kB/s eta 0:00:04
   ----------------------------- ---------- 1.3/1.8 MB 222.2 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 222.2 kB/s eta 0:00:03
   ---------------------------------- ----- 1.6/1.8 MB 255.1 kB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 255.1 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 281.4 kB/s  0:00:06
Using cached regex-2026.7.19-cp313-cp313-win_amd64.whl (277 kB)
Installing collected packages: regex, nltk

   ---------------------------------------- 0/2 [regex]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed nltk-3.10.3 regex-2026.7.19
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script nltk.exe is installed in 'C:\Users\rajes\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
remove_stopwords