# pandas series

In [24]:
import pandas as pd
a=[1,2,3,4,5]
se=pd.Series(a)
se

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [25]:
type(se)

pandas.Series

# change index name

In [26]:
import pandas as pd
a=[1,2,3,4,5]
se=pd.Series(a ,index=['a','b','c','d','e'])
se

a    1
b    2
c    3
d    4
e    5
dtype: int64

# DataFrame

In [27]:
# using list
import pandas as pd
data=[1,2,3,4,5]
df=pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4
4  5

In [28]:
#using dict
fruits={'fruit':['apple','banana','orange'],'quantity':[10,20,30]}
df=pd.DataFrame(fruits)
df

    fruit  quantity
0   apple        10
1  banana        20
2  orange        30

# creating DataFrame using numpy array

In [29]:
import numpy as np
nparry=np.array([[5000,6000],['Raj','Ravi']])
df=pd.DataFrame({'name':nparry[1],'salary':nparry[0]})
df

   name salary
0   Raj   5000
1  Ravi   6000

# merze operation

In [30]:
# merze operation
player=['player1','player2','player3']
points=[8,9,6]
title=['game1','game2','game3']
df1=pd.DataFrame({'player':player,'points':points})
print(df1)
df2=pd.DataFrame({'player':player,'title':title})
print(df2)
df3=pd.merge(df1,df2,on='player')
df3

    player  points
0  player1       8
1  player2       9
2  player3       6
    player  title
0  player1  game1
1  player2  game2
2  player3  game3

    player  points  title
0  player1       8  game1
1  player2       9  game2
2  player3       6  game3

In [31]:
# merze operation
player=['player1','player2','player3']
points=[8,9,6]
title=['game1','game2','game3']
df1=pd.DataFrame({'player':player,'points':points,'title':title})
df1

    player  points  title
0  player1       8  game1
1  player2       9  game2
2  player3       6  game3

In [32]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df2=pd.DataFrame({'player':player,'power':power,'title':title})
df2

    player  power  title
0  player1  punch  game1
1  player5   kick  game5
2  player6  block  game6

# innermerze

In [33]:
df3=pd.merge(df1,df2,on='player',how='inner')
df3

    player  points title_x  power title_y
0  player1       8   game1  punch   game1

In [34]:
df4=pd.merge(df1,df2,on='title',how='inner')
df4

  player_x  points  title player_y  power
0  player1       8  game1  player1  punch

left merze

In [35]:
df5=pd.merge(df1,df2,on='player',how='left')
df5

    player  points title_x  power title_y
0  player1       8   game1  punch   game1
1  player2       9   game2    NaN     NaN
2  player3       6   game3    NaN     NaN

Right merze

In [36]:
df6=pd.merge(df1,df2,on='player',how='right')
df6

    player  points title_x  power title_y
0  player1     8.0   game1  punch   game1
1  player5     NaN     NaN   kick   game5
2  player6     NaN     NaN  block   game6

In [37]:
df7=pd.merge(df1,df2,on='player',how='outer')
df7

    player  points title_x  power title_y
0  player1     8.0   game1  punch   game1
1  player2     9.0   game2    NaN     NaN
2  player3     6.0   game3    NaN     NaN
3  player5     NaN     NaN   kick   game5
4  player6     NaN     NaN  block   game6

# Join oparation

In [38]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df10=pd.DataFrame({'player':player,'power':power,'title':title},index=['l1','l2','l3'])
df10

     player  power  title
l1  player1  punch  game1
l2  player5   kick  game5
l3  player6  block  game6

In [39]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df12=pd.DataFrame({'player':player,'power':power,'title':title},index=['l2','l3','l4'])
df12

     player  power  title
l2  player1  punch  game1
l3  player5   kick  game5
l4  player6  block  game6

inner join

In [40]:
# inner join with suffixes to avoid overlapping column names
# original error occurred because both DataFrames shared identical column names

result = df10.join(df12, how='inner', lsuffix='_10', rsuffix='_12')
result

   player_10 power_10 title_10 player_12 power_12 title_12
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5

In [41]:
df3=df10.join(df12, how='left', lsuffix='_10', rsuffix='_12')
df3

   player_10 power_10 title_10 player_12 power_12 title_12
l1   player1    punch    game1       NaN      NaN      NaN
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5

In [42]:
df3=df10.join(df12, how='right', lsuffix='_10', rsuffix='_12')
df3

   player_10 power_10 title_10 player_12 power_12 title_12
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5
l4       NaN      NaN      NaN   player6    block    game6

# concatanate